<!DOCTYPE html>
<html lang="en">
 
        <!-- Navigation-->
        
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Liste d'articles</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                  
                    <!-- Post preview-->
                    <?php foreach($articles as $article): ?>
                    <div class="post-preview" >
                        <a href="post.php?post_id=<?= htmlspecialchars($article['Id']); ?>" >
                            <h2 class="post-title"><?= htmlspecialchars($article['Title']);?></h2>
                        </a>
                        <h3 class="post-subtitle"><?= htmlspecialchars($article['Name']); ?></h3>
                        <p class="post-meta">
                           Posted by <?= htmlspecialchars($article['LastName'])." ".htmlspecialchars($article['FirstName']); ?>
                            on <?= htmlspecialchars($article['DATE']); ?>
                        </p>
                        <p><?= htmlspecialchars($article['content']); ?></p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <?php endforeach; ?>
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
               
</html>
