<!DOCTYPE html>
<html lang="en">
 
        <!-- Navigation-->

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
            
            <p>Administration/gestion des articles/Créer un nouvel article</p>
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Rédiger un article</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                
                <form action="addArticle.php" method="post">
                <label for="">Catégorie de l'article</label>
                <select class="form-select mb_4" name="category">
                    <?php foreach($categories as $categorie): ?>
                        <option  value="<?= htmlspecialchars($categorie['Id']); ?>" ><?= htmlspecialchars($categorie['Name']); ?></option> 
                    <?php endforeach; ?>                    
                </select>

                <label for="">Auteur</label>
                <select class="form-select mb_4" name="author">
                    <?php foreach($authors as $author): ?>
                        <option value="<?= htmlspecialchars($author['Id']); ?>" ><?= htmlspecialchars($author['FirstName'])." ".htmlspecialchars($author['LastName']); ?></option>
                    <?php endforeach; ?>
                </select>

                <label for="">Titre de l'article</label>
<br>
                <input type="text" name="titre" >
<br>
                <label for="">Texte de l'article</label><br>
                <textarea name="contenue" id="" cols="70" rows="10"></textarea>
<br>
                <button type="submit" class="btn btn-primary mb-4 mt-4">Enregister</button>
                </form>

                </div>
            </div>
        </div>
               
</html>
